export const GET_TODOS_START = "GET_TODOS_START";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const SET_TODOS_START = "SET_TODOS_START";
export const SET_TODOS_SUCCESS = "SET_TODOS_SUCCESS";
export const SET_TODOS_FAILURE = "SET_TODOS_FAILURE";

export const SET_TODO_CATEGORIES = "SET_TODO_CATEGORIES";
export const SET_TODO_FILTERS = "SET_TODO_FILTERS";
